init arm64

diff --git a/mkimage-profiles/bin/tar2fs b/mkimage-profiles/bin/tar2fs
--- a/mkimage-profiles/bin/tar2fs
+++ b/mkimage-profiles/bin/tar2fs
@@ -31,16 +31,24 @@ INITRD_MODULES=
 BOOTFSTYPE=
 BOOTPART=
 
-case "`arch`" in	# NB: sudo => no GLOBAL_ will do either; mind qemu-*
+ARCH="$(arch)"		# NB: sudo => no GLOBAL_ will do either; mind qemu-*
+
+case "$ARCH" in
 *86*)
 	# NB: different storage modules might be needed for non-kvm
-	INITRD_MODULES="sd_mod ata_piix ahci"
+	INITRD_MODULES="sd_mod ata_piix ahci virtio-scsi virtio-blk"
 	BLOCKDEV="/dev/sda"	# might be /dev/vda for virtio
 	ROOTPART="1"
 	;;
 arm*)
 	BOOTFSTYPE="ext2"	# support expected in every sane target uboot
 	BLOCKDEV="/dev/mmcblk0p"	# ...hopefully...
+	BOOTPART="1"
+	ROOTPART="2"
+	;;
+e2k)
+	BOOTFSTYPE="ext2"       # firmware knows it
+	BLOCKDEV="/dev/sda"     # ...hopefully...
 	BOOTPART="1"
 	ROOTPART="2"
 	;;
@@ -130,7 +138,10 @@ exit_handler() {
 		umount ${BOOTFS:+"$BOOTFS"} "$ROOTFS"{/dev,/proc,/sys,}
 
 		if [ -n "$LOOPDEV" ]; then
-			kpartx -d -s "$LOOPDEV"
+			kpartx -d -s "$LOOPDEV" || {
+				sleep 10
+				kpartx -d -s -v "$LOOPDEV"
+			}
 			losetup --detach "$LOOPDEV"
 		fi
 		rm -r -- "$ROOTFS"
@@ -204,11 +215,31 @@ fi
 
 echo "MODULES_PRELOAD += $INITRD_MODULES $ROOTFSTYPE" >> "$ROOTFS/etc/initrd.mk"
 
-KERNEL="$(readlink $ROOTFS/boot/vmlinuz | sed 's,vmlinuz-,,')"
-chroot "$ROOTFS" make-initrd -k "$KERNEL"
+case "$ARCH" in
+*86*)
+	echo "FEATURES += qemu" >> "$ROOTFS/etc/initrd.mk"
+	;;
+e2k)
+	echo "FEATURES += usb"  >> "$ROOTFS/etc/initrd.mk"
+	;;
+esac
+
+# NB: don't stick BOOTFS here, it has slightly different semantics
+pushd $ROOTFS/boot
+if [ -s .origver ]; then
+	read KVER < .origver
+fi
+[ -n "$KVER" ] || fatal "unable to deduce kernel version"
+chroot "$ROOTFS" make-initrd -k "$KVER"
+rm -f .origver
 
 # ...target device too
 sed -i "s,$LOOPROOT,$ROOTDEV," "$ROOTFS/etc/fstab"
+
+if [ -f boot.conf ]; then
+	sed -i -e "s,@ROOTUUID@,$ROOTUUID,g" -e "s,@KVER@,$KVER,g" boot.conf
+fi
+popd
 
 if [ -x "$ROOTFS"/sbin/lilo ]; then
 	# configure and install bootloader
@@ -220,7 +251,7 @@ delay=1
 vga=0
 image=/boot/vmlinuz
   initrd=/boot/initrd.img
-  append=\"root=$ROOTDEV rootdelay=3 quiet\"
+  append=\"root=$ROOTDEV rootdelay=3 console=tty1 console=ttyS0,115200n8\"
   label=linux"
 
 	cat > "$ROOTFS"/etc/lilo-loop.conf <<-EOF
@@ -244,5 +275,5 @@ image=/boot/vmlinuz
 fi
 
 if [ -n "$SUDO_USER" ]; then
-	chown "$SUDO_USER" "$IMG" "$ROOTFS" "$WORKDIR"
+	chown "$SUDO_USER:$(id -g "$SUDO_USER")" "$IMG" "$ROOTFS" "$WORKDIR" ||:
 fi
diff --git a/mkimage-profiles/image.in/Makefile b/mkimage-profiles/image.in/Makefile
--- a/mkimage-profiles/image.in/Makefile
+++ b/mkimage-profiles/image.in/Makefile
@@ -1,4 +1,4 @@
-# stage 4: dive into mkimage
+# step 4: dive into mkimage
 
 GLOBAL_BUILDDIR ?= $(shell pwd)
 CURRENT_LINK := mkimage-profiles
@@ -80,6 +80,10 @@ imagedir:
 
 postprocess: | $(addprefix postprocess-,$(sort $(POSTPROCESS_TARGETS)))
 	@OUTSIZE="`ls -lh "$(IMAGE_OUTPATH)" | cut -f5 -d' '`"; \
+	if [ ! -n "$$OUTSIZE" ]; then \
+		echo "** error: $(IMAGE_OUTPATH) missing" >&2; \
+		exit 1; \
+	fi; \
 	echo "** image: $(IMAGE_OUTPATH) [$$OUTSIZE]" >&2 && \
 	echo "IMAGE_OUTPATH = $(IMAGE_OUTPATH)" && \
 	echo "IMAGE_OUTFILE = $(IMAGE_OUTFILE)" && \
@@ -92,7 +96,7 @@ postprocess: | $(addprefix postprocess-,$(sort $(POSTPROCESS_TARGETS)))
 		cp -a distcfg.mk "$(LOGDIR)/$(IMAGE_OUTFILE).cfg"; \
 	fi
 
-debug:
+debug::
 	@echo "TOPDIR=$(TOPDIR)"
 	@echo "IMAGEDIR=$(IMAGEDIR)"
 	@echo "ARCH=$(ARCH)"
